FROM iotedgedev-windows-base
ARG IOTEDGEDEV_VERSION
COPY iotedgedevtest-$IOTEDGEDEV_VERSION-py2.py3-none-any.whl dist/iotedgedevtest-latest-py2.py3-none-any.whl
RUN pip install dist/iotedgedev-latest-py2.py3-none-any.whl